Prevent linker errors with shared boost unit test libs.
If we are using a shared boost unit test library we need
to define BOOST_TEST_DYN_LINK or we will get linker error
like:
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status

With this commit we do this in the source files of all the tests like in
other modules by checking HAVE_DYNAMIC_BOOST_TEST and if it is defined
setting BOOST_TEST_DYN_LINK.